### PR TITLE
I added two options so you can control the colors of the generated QR Code

### PR DESCRIPTION
**Pull request by johndgiese**

### CODE REVIEW

**Comment by monospaced** [comment]
thanks for the contribution :)

I will have a think about this one (yes I know it has been months already, sorry about that !).

**Comment by johndgiese** [comment]
Ideally this would be handled with CSS, but I don't think you can do this with canvas, right?  So if you can't change the color here, how are you going to change it?

**Comment by bitjson** [comment]
If you're interested, this fork pulls in colorization options, and is used in several production applications (so it will continue to be maintained): https://github.com/bitpay/angular-qrcode/

**Comment by monospaced** [comment]
Thanks for the contribution 👍 , color functionality has now been added 26c8e3e

**Pull request closed without merging**
